version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      gha:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directories:
      - /
      - /build
    schedule:
      interval: weekly
    allow:
      - dependency-type: all
    ignore:
      # Latest version incompatible with buf
      - dependency-name: github.com/quic-go/quic-go
    groups:
      go:
        patterns:
          - "*"
