name: CI
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: wasilibs/actions/.github/workflows/ci.yaml@5bf268fde802fe591d6148e69a7ddb046384d657
    secrets: inherit

  example:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: curioswitch/go-build/.github/actions/setup-go@a2e54f5c6b6cff10d3b5ac6fcba4de7a411c6736 # v0.8.1

      - name: build example
        run: go run ./build example
