name: "Release"

on:
  push:
    tags:
      - v*

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  release:
    uses: wasilibs/actions/.github/workflows/release.yaml@c6c4d5418f5f5ad5a25bba3ca44875c4ed1e9564
    secrets: inherit
