name: "Release"

on:
  push:
    tags:
      - v*

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  release:
    uses: wasilibs/actions/.github/workflows/release.yaml@77762dfec6f9722d1b57acdfe352dcd16a1dc272
    secrets: inherit
